import React from "react";
import { NavLink, useLocation } from "react-router-dom";
import * as I from "lucide-react";
import VisualInfographic from "../VisualInfographic";
import { useSession } from "./SessionContext";

export const PROFILE_LABELS = { dyslexia: "Dyslexia", cognitive_load: "Cognitive load support", low_vision: "Low vision and clarity" };

export function Layout({ children, section }) {
  const location = useLocation();
  const { session } = useSession();
  const items = [["/upload", "Upload", I.CloudUpload], ["/learn", "Learn", I.BookOpen], ["/practice", "Practice", I.BadgeHelp], ["/progress", "Progress", I.BarChart3]];
  return <div className="app-container"><div className="desktop-layout"><aside className="desktop-sidebar"><NavLink to="/progress" className="brand" style={{ marginBottom: 12 }}><div className="logo">A</div><div><div className="brandname">AdaptLearn</div></div></NavLink><nav className="sidebar-nav">{items.map(([to, label, Icon]) => <NavLink key={to} to={to} className={`sidebar-link ${location.pathname === to ? "active" : ""}`}><Icon size={18} /><span>{label}</span></NavLink>)}</nav><div style={{ padding: 14, background: "linear-gradient(135deg, rgba(238, 242, 255, 0.8), rgba(245, 243, 257, 0.8))", borderRadius: 14, border: "1px solid rgba(199, 210, 254, 0.6)", marginTop: "auto" }}><div style={{ fontSize: 10, fontWeight: 800, color: "var(--primary)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Active Profile</div><div style={{ fontSize: 13, fontWeight: 700, color: "var(--ink)", marginTop: 4 }}>{PROFILE_LABELS[session.profile]}</div>{session.fileName && <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 6, display: "flex", alignItems: "center", gap: 5 }}><I.FileText size={12} /><span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{session.fileName}</span></div>}</div></aside><div className="main-content"><header className="topbar"><NavLink to="/progress" className="brand"><div className="logo">A</div><div><div className="brandname">AdaptLearn</div><div className="subtitle">{section}</div></div></NavLink><div className="header-right">{session.rewireState?.active && <span className="rewire-tag"><I.Zap size={12} style={{ marginRight: 4 }} /> REWIRED</span>}<div className="access-badge"><span className="access-dot" /><span>{PROFILE_LABELS[session.profile]}</span></div><div className="avatar">AL</div></div></header>{children}</div></div><nav className="bottom-nav">{items.map(([to, label, Icon]) => <NavLink key={to} to={to} className={`nav-item ${location.pathname === to ? "active" : ""}`}><Icon /><span>{label}</span></NavLink>)}</nav></div>;
}

export function ErrorNotice() { const { session } = useSession(); return session.error ? <div style={{ background: "var(--amber-light)", border: "1px solid #fde68a", color: "#92400e", padding: "12px 16px", borderRadius: 12, marginTop: 14, fontSize: 13, display: "flex", alignItems: "center", gap: 10 }}><I.AlertCircle size={18} style={{ flexShrink: 0 }} /><span>{session.error}</span></div> : null; }

export function VisualCard({ visual, onReadAloud }) {
  if (!visual) return null;
  const { source = "prism", title = "", subtitle = "", explanation = "", key_takeaways = [], why_visual = "", svg_html = null, source_images = [], spec = {}, error = null } = visual;
  if (error) return <section className="card" style={{ padding: 18, marginTop: 16 }}><div style={{ display: "flex", alignItems: "center", gap: 10, color: "#b91c1c" }}><I.AlertCircle size={20} /><span>{error}</span></div></section>;
  return <section className="card" style={{ marginTop: 16, padding: 20 }}><div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 14 }}><div style={{ flex: 1 }}><span className="pill" style={{ background: source === "pdf" ? "#fef3c7" : "var(--primary-light)", color: source === "pdf" ? "#92400e" : "var(--primary)", marginBottom: 6 }}>{source === "pdf" ? "SOURCE VISUAL" : "EDUCATIONAL INFOGRAPHIC"}</span>{title && <h2 style={{ fontFamily: "var(--font-heading)", fontSize: 18, margin: "4px 0 0", color: "var(--ink)" }}>{title}</h2>}{subtitle && <p style={{ fontSize: 13, color: "var(--muted)", margin: "4px 0 0" }}>{subtitle}</p>}</div></div><VisualInfographic spec={spec} sourceImages={source_images} svgHtmlFallback={svg_html} onReadAloud={onReadAloud} />{explanation && <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid var(--border-color)" }}><b style={{ fontSize: 12, fontWeight: 800, color: "var(--primary)", textTransform: "uppercase", letterSpacing: "0.05em", display: "flex", alignItems: "center", gap: 6 }}><I.Lightbulb size={14} /> Understand It</b><p style={{ fontSize: 14, lineHeight: 1.6, color: "#334155", marginTop: 4 }}>{explanation}</p></div>}{key_takeaways.length > 0 && <div style={{ marginTop: 12 }}><b style={{ fontSize: 12, fontWeight: 800, color: "var(--primary)", textTransform: "uppercase", letterSpacing: "0.05em" }}>Key Takeaways</b><ul style={{ marginTop: 6, paddingLeft: 20 }}>{key_takeaways.map((t, i) => <li key={i} style={{ fontSize: 13, color: "#334155", marginBottom: 4, lineHeight: 1.5 }}>{t}</li>)}</ul></div>}{why_visual && <div className="visual-description-box" style={{ marginTop: 12 }}><span style={{ fontWeight: 700, color: "#854d0e" }}>Why this infographic? </span><span style={{ color: "#713f12" }}>{why_visual}</span></div>}{explanation && <button className="secondary-action" style={{ marginTop: 14, fontSize: 12, padding: "8px 14px" }} onClick={() => onReadAloud && onReadAloud(explanation + " " + key_takeaways.join(". "))}><I.Volume2 size={14} /> Read explanation</button>}</section>;
}