import React from "react";
import * as I from "lucide-react";
import { useSession } from "../shared/SessionContext";
import { Layout, PROFILE_LABELS } from "../shared/Shared";
import { evaluateSignals } from "../../engine/signals";
import "./Progress.css";

export default function Progress() {
  const { session } = useSession();
  const transformed = Boolean(session.transformed); const chunks = session.transformed?.profile === "cognitive_load" ? session.transformed.chunks.length : transformed ? 1 : 0; const evaluation = evaluateSignals(session.signals, session.sessionMeta); const history = session.sessionMeta.adaptationHistory || []; const latestOutcome = session.latestOutcome;
  return <Layout section="Progress"><main className="page progress-page"><div className="eyebrow"><b>Session Progress</b><span>{session.fileName || "No lesson loaded"}</span></div><h1 className="page-title">Your learning session</h1><div className="stats-grid"><div className="stat"><b>{session.wordCount}</b><span>Source Words</span></div><div className="stat"><b>{chunks}</b><span>Learning Chunks</span></div><div className="stat"><b>{session.quizzes.length + session.practiceReport.answered.length}</b><span>Questions Answered</span></div><div className="stat"><b>{session.practiceReport.masteredSections.length || session.completed}</b><span>Sections Mastered</span></div></div><section className="card telemetry-card"><div className="progress-card-heading"><span className="pill"><I.Activity size={13} /> SCALE Cognitive Telemetry</span><span>Variant Level: {session.sessionMeta.currentVariantLevel}</span></div><div className="score-row"><b>Current Struggle Score</b><b>{(evaluation.struggleScore * 100).toFixed(0)}% / 100%</b></div><div className="progressbar"><div className="progressfill" style={{ width: `${Math.min(100, evaluation.struggleScore * 100)}%` }} /></div><div className="telemetry-stats"><div><span>Total Adaptations</span><b>{session.sessionMeta.totalAdaptations}</b></div><div><span>Latest Outcome Delta</span><b>{latestOutcome ? `+${((latestOutcome.outcomeDelta || 1) * 100).toFixed(0)}%` : "N/A"}</b></div></div></section><section className="card adaptation-log"><b>Cognitive Adaptation Log</b><p>Real-time interventions triggered by the SCALE behavioral engine.</p>{history.length === 0 ? <div className="empty-log">No struggle adaptations triggered in this session yet.</div> : history.map((rec) => <div className="history-item" key={rec.id}><div><b>Level {rec.previousLevel} to Level {rec.newLevel}</b><span>Struggle Score: {(rec.struggleScore * 100).toFixed(0)}%</span></div><p>{rec.explanation}</p></div>)}</section><section className="card progress-summary"><span className="pill">{PROFILE_LABELS[session.profile]}</span><h2>{transformed ? "Lesson adapted & active" : "Ready to begin"}</h2><p>{transformed ? "Your transformed lesson, practice questions, section mastery tracker, and cognitive adaptations are available across the learning flow." : "Upload a document or choose a profile to start your study session."}</p></section></main></Layout>;
}